import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";
import StoreProvider from "@/lib/StoreProvider";
import Loader from "@/components/Loader";
import logo from "@/public/images/logo.png";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "إقامات أبواب بوسكورة GH 3",
  description: "Generated by create next app",
  icons: logo.src
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoreProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <Loader />

          <NavBar />
          {children}
        </body>
      </html>
    </StoreProvider>
  );
}
